import query from "../config/db.js";

// Get fields to return publicly
const CATEGORY_FIELDS = "id, unique_id, name, created_at";

// Create a new category
export const createCategory = async (name: string) => {
  // unique_id is automatically generated by PostgreSQL (UUID DEFAULT gen_random_uuid())
  const text = `INSERT INTO categories(name) VALUES($1) RETURNING ${CATEGORY_FIELDS}`;
  const res = await query(text, [name]);
  return res.rows[0];
};

// Retrieve all categories
export const findAllCategories = async () => {
  const text = `SELECT ${CATEGORY_FIELDS} FROM categories ORDER BY name ASC`;
  const res = await query(text);
  return res.rows;
};

// Retrieve a single category by ID
export const findCategoryById = async (id: number) => {
  const text = `SELECT ${CATEGORY_FIELDS} FROM categories WHERE id = $1`;
  const res = await query(text, [id]);
  return res.rows[0];
};

// Update a category name
export const updateCategory = async (id: number, name: string) => {
  const text = `UPDATE categories SET name = $1 WHERE id = $2 RETURNING ${CATEGORY_FIELDS}`;
  const res = await query(text, [name, id]);
  return res.rows[0];
};

// Delete a category
export const deleteCategory = async (id: number) => {
  // ON DELETE CASCADE on the 'products' table will handle deletion of linked products
  const text = `DELETE FROM categories WHERE id = $1 RETURNING ${CATEGORY_FIELDS}`;
  const res = await query(text, [id]);
  return res.rows[0];
};
